### ISSUE TITLE
Block comments for .razor are using <!-- --> and //

### ISSUE THREAD

**Issue by o-lee** [LoneBoco/razor-sublime#2]
I'm using ST4 on a Mac, when select multiple lines and click `CMD + /` I get 2 different types of comments depending where I am in the code (See screenshot). I'm expecting to see `@* *@`. I've tried changing Comments.tmPreferences following [this](https://stackoverflow.com/questions/44555213/in-sublime-text-3-how-can-i-change-the-comment-character/44582720#44582720), however it uses the correct syntax.
<img width="581" alt="Screen Shot 2022-12-22 at 8 34 23 AM" src="https://user-images.githubusercontent.com/9204410/209168733-0dac4d01-382b-4f9c-a042-8b6e55a16266.png">

**Comment by LoneBoco** [comment]
Would you be interested in seeing Razor comments in all situations?  While editing HTML and while editing C#?

**Comment by LoneBoco** [comment]
Resolved in release 1.0.6.
